# Generated by Django 4.2 on 2023-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
